### ISSUE TITLE
Update instruction to download installer script to home directory

### ISSUE THREAD

**Issue by patelgr** [unixabg/raspi-helpers#3]
Update instruction to download installer script to home directory and execute from home directory

**Comment by unixabg** [comment]
I did just a bit of format adjustments on the README.md, but if the commands are followed in sequence I believe no need to add such things as --directory-prefix= to the wget and the fully qualified path for the chmod command.

**Comment by patelgr** [comment]
Hi unixabg,

As the script is download all zip packages and executes files relative to home directory 

either before executing wget we need to cd to home directory or the instruction needs to specify go to home directory

**Comment by unixabg** [comment]
Greetings,
I believe your concern is addressed in line 62 of scripts/jasper-installer.sh.
Thanks.
