### ISSUE TITLE
Osmc run

### ISSUE THREAD

**Issue by lowdev** [unixabg/raspi-helpers#4]
Hey !
Thank you for your script !!! It's awesome.
However i had some little issues (i run on osmc it's based on debian):
- No such file or directory: '/home/pi/.bashrc'
  -> Replace "pi" by your user
- On jessie sudo apt-get install libportaudio-dev won't work
  -> Remove the dependency
- No such file or directory: '/root/jasper/client/requirements.txt'
  -> i replaced "~/jasper/client/requirements.txt" by my own path "/home/osmc/jasper/...."

**Comment by lowdev** [comment]
I had this error when i launch jasper :
- ValueError: STT engine 'sphinx' is not available (due to missing dependencies, missing dependencies, etc.)
  -> sudo apt-get install python-pocketsphinx
  - NameError: global name 'cmuclmtk' is not defined
    -> https://jasperproject.github.io/documentation/installation/  Installing CMUCLMTK
    -> Installing Phonetisaurus, m2m-aligner and MITLM

**Comment by unixabg** [comment]
Greetings,

Glad you like. Please know that the script is designed and tested for Raspbian, per README.md

```
Script to assist installing Jasper on Raspbian Lite
Tested on a fresh install of Jessie Raspbian Lite and expanded to use entire disk
```

If you want to adjust to run on something other than Raspbian, best to fork and develop as you wish.

Thanks.
